###########################
# Copyright               #
# © 2020 Kártyás Bálint.  #
# All rights reserved.    #
###########################

version: '3.7'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    network_mode: "host"
    volumes:
      #- /:/config
      - /etc/localtime:/etc/localtime:ro
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.1
    network_mode: "host"
    volumes:
      - influxData:/var/lib/influxdb

volumes:
  influxData:
