version: '3.7'
services:
  telegraph:
    image: telegraf:1.16.2
    network_mode: "host"
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.1
    ports:
      - "8086:8086"
    volumes:
      - influxData:/var/lib/influxdb

volumes:
  influxData:
