version: '3.7'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    network_mode: "host"
    volumes:
      #- /:/config
      - /etc/localtime:/etc/localtime:ro
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.1
    ports:
      - "8086:8086"
    volumes:
      - influxData:/var/lib/influxdb

volumes:
  influxData:
